import { Injectable } from '@angular/core';
import { Product, ProductCategory } from '../../shared/models/product.model';

/** Portadas oficiales vía Steam CDN (library_600x900 + variantes para galería). */
function steam(appId: string): { image: string; images: string[] } {
  const base = `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}`;
  return {
    image: `${base}/library_600x900.jpg`,
    images: [
      `${base}/library_600x900.jpg`,
      `${base}/header.jpg`,
      `${base}/capsule_616x353.jpg`,
      `${base}/library_hero.jpg`,
    ],
  };
}

const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Horizon Zero Dawn Edición Completa',
    description:
      'Vendo mi juego de Horizon Zero Dawn, disco en perfecto estado. Precio negociable. Pregunte sin compromiso (Entrega gratis en Mega Plaza).',
    price: 40,
    category: 'games',
    ...steam('1151640'),
    tags: ['ps4', 'acción', 'aventura', 'horizon'],
    stock: 5,
    rating: 4.8,
    seminuevo: true,
    featured: true,
    platform: 'PS4 / PS5',
    genre: 'Acción / Aventura',
    ageRating: 'Adolescentes',
    specs: {
      Plataforma: 'PS4 / PS5',
      Género: 'Acción / Aventura',
      Condición: 'Seminuevo',
    },
  },
  {
    id: '2',
    name: 'God of War',
    description:
      'God of War (2018) en excelente estado. Historia épica de Kratos y Atreus. Disco sin rayones.',
    price: 55,
    category: 'games',
    ...steam('1593500'),
    tags: ['ps4', 'acción', 'aventura', 'god of war'],
    stock: 4,
    rating: 4.9,
    seminuevo: true,
    featured: true,
    platform: 'PS4 / PS5',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '3',
    name: "Marvel's Spider-Man Remastered",
    description:
      'Spider-Man Remastered. Balancea por Nueva York en perfecto estado. Entrega en Cajamarca.',
    price: 70,
    category: 'games',
    ...steam('1817070'),
    tags: ['ps5', 'acción', 'spider-man'],
    stock: 6,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '4',
    name: 'The Last of Us Parte I',
    description:
      'The Last of Us Parte I remasterizado. Experiencia cinematográfica completa. Seminuevo.',
    price: 85,
    category: 'games',
    ...steam('1888930'),
    tags: ['ps5', 'aventura', 'tlou'],
    stock: 3,
    rating: 4.8,
    seminuevo: true,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '5',
    name: "Ghost of Tsushima Director's Cut",
    description:
      "Ghost of Tsushima Director's Cut. Mundo abierto samurái con expansión Iki Island incluida.",
    price: 95,
    category: 'games',
    ...steam('2215430'),
    tags: ['ps5', 'acción', 'mundo abierto'],
    stock: 4,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '6',
    name: 'Elden Ring',
    description:
      'Elden Ring edición estándar. Mundo abierto FromSoftware. Disco en perfecto estado.',
    price: 110,
    category: 'games',
    ...steam('1245620'),
    tags: ['ps5', 'rpg', 'souls'],
    stock: 5,
    rating: 4.9,
    featured: true,
    platform: 'PS4 / PS5',
    genre: 'RPG / Acción',
    ageRating: 'Adultos',
  },
  {
    id: '7',
    name: 'Cyberpunk 2077',
    description:
      'Cyberpunk 2077 actualizado. Explora Night City en seminuevo, precio negociable.',
    price: 60,
    category: 'games',
    ...steam('1091500'),
    tags: ['ps5', 'rpg', 'cyberpunk'],
    stock: 7,
    rating: 4.5,
    seminuevo: true,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '8',
    name: 'Red Dead Redemption 2',
    description:
      'RDR2 edición estándar. Mundo abierto western de Rockstar. Disco impecable.',
    price: 65,
    category: 'games',
    ...steam('1174180'),
    tags: ['ps4', 'aventura', 'western'],
    stock: 4,
    rating: 4.9,
    featured: true,
    platform: 'PS4',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '9',
    name: 'Grand Theft Auto V',
    description:
      'GTA V Premium Edition. Incluye acceso a GTA Online. Seminuevo, entrega inmediata.',
    price: 45,
    category: 'games',
    ...steam('271590'),
    tags: ['ps4', 'acción', 'gta'],
    stock: 8,
    rating: 4.7,
    seminuevo: true,
    featured: true,
    platform: 'PS4 / PS5',
    genre: 'Acción',
    ageRating: 'Adultos',
  },
  {
    id: '10',
    name: 'Days Gone',
    description:
      'Days Gone. Supervivencia post-apocalíptica en moto. Disco en excelente estado.',
    price: 35,
    category: 'games',
    ...steam('1259420'),
    tags: ['ps4', 'supervivencia', 'acción'],
    stock: 6,
    rating: 4.4,
    seminuevo: true,
    featured: true,
    platform: 'PS4 / PC',
    genre: 'Acción / Supervivencia',
    ageRating: 'Adultos',
  },
  {
    id: '11',
    name: 'Uncharted: Legacy of Thieves',
    description:
      'Colección Uncharted: Legacy of Thieves Collection. Incluye Uncharted 4 y Lost Legacy.',
    price: 75,
    category: 'games',
    ...steam('1659420'),
    tags: ['ps5', 'aventura', 'uncharted'],
    stock: 3,
    rating: 4.8,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '12',
    name: 'Resident Evil 4 Remake',
    description:
      'Resident Evil 4 Remake. Terror de acción renovado. Disco sin rayones.',
    price: 100,
    category: 'games',
    ...steam('2050650'),
    tags: ['ps5', 'terror', 'acción'],
    stock: 4,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Terror / Acción',
    ageRating: 'Adultos',
  },
  {
    id: '13',
    name: 'Mortal Kombat 11',
    description:
      'Mortal Kombat 11. Luchas brutales con roster completo. Seminuevo.',
    price: 40,
    category: 'games',
    ...steam('976310'),
    tags: ['ps4', 'lucha', 'mk'],
    stock: 9,
    rating: 4.5,
    seminuevo: true,
    platform: 'PS4',
    genre: 'Lucha',
    ageRating: 'Adultos',
  },
  {
    id: '14',
    name: 'FIFA 23',
    description:
      'FIFA 23. Fútbol con licencias oficiales. Ideal para jugar en local o online.',
    price: 50,
    category: 'games',
    ...steam('1811260'),
    tags: ['ps5', 'deportes', 'fifa'],
    stock: 7,
    rating: 4.3,
    seminuevo: true,
    platform: 'PS5',
    genre: 'Deportes',
    ageRating: 'Todos',
  },
  {
    id: '15',
    name: 'Call of Duty: Modern Warfare II',
    description:
      'Modern Warfare II. Campaña y multiplayer. Disco en perfecto estado.',
    price: 90,
    category: 'games',
    ...steam('1938090'),
    tags: ['ps5', 'shooter', 'cod'],
    stock: 5,
    rating: 4.4,
    platform: 'PS5',
    genre: 'Shooter',
    ageRating: 'Adultos',
  },
  {
    id: '16',
    name: 'Hogwarts Legacy',
    description:
      'Hogwarts Legacy. Vive el mundo mágico de Harry Potter en mundo abierto.',
    price: 105,
    category: 'games',
    ...steam('990080'),
    tags: ['ps5', 'rpg', 'aventura'],
    stock: 4,
    rating: 4.6,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'RPG / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '17',
    name: 'Star Wars Jedi: Fallen Order',
    description:
      'Star Wars Jedi: Fallen Order. Aventura souls-like en el universo Star Wars.',
    price: 45,
    category: 'games',
    ...steam('1172380'),
    tags: ['ps4', 'acción', 'star wars'],
    stock: 6,
    rating: 4.7,
    seminuevo: true,
    platform: 'PS4 / PS5',
    genre: 'Acción / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '18',
    name: 'Ratchet & Clank: Rift Apart',
    description:
      'Ratchet & Clank: Rift Apart. Plataformas dimensionales en 4K. Como nuevo.',
    price: 115,
    category: 'games',
    ...steam('1895880'),
    tags: ['ps5', 'plataformas', 'aventura'],
    stock: 3,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'Plataformas / Aventura',
    ageRating: 'Todos',
  },
  {
    id: '19',
    name: 'PlayStation 5 Slim',
    description:
      'Consola PS5 Slim 1TB con un mando DualSense y cables originales. Seminueva.',
    price: 2200,
    category: 'consoles',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
    ],
    tags: ['ps5', 'consola'],
    stock: 2,
    rating: 4.9,
    seminuevo: true,
    featured: true,
    platform: 'PS5',
    genre: 'Consolas',
    ageRating: 'Todos',
  },
  {
    id: '20',
    name: 'PlayStation 4 Slim 1TB',
    description:
      'Consola PS4 Slim 1TB en excelente estado, con un mando y cables originales.',
    price: 850,
    category: 'consoles',
    image: 'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&h=800&fit=crop',
    ],
    tags: ['ps4', 'consola'],
    stock: 3,
    rating: 4.7,
    seminuevo: true,
    platform: 'PS4',
    genre: 'Consolas',
    ageRating: 'Todos',
  },
  {
    id: '21',
    name: 'DualSense PS5 Blanco',
    description:
      'Mando DualSense original para PS5. Feedback háptico y gatillos adaptativos.',
    price: 280,
    category: 'peripherals',
    image: 'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
    ],
    tags: ['ps5', 'mando', 'dualsense'],
    stock: 10,
    rating: 4.8,
    featured: true,
    platform: 'PS5',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '22',
    name: 'DualShock 4 Original',
    description:
      'Mando DualShock 4 original para PS4. Batería en buen estado. Color negro.',
    price: 120,
    category: 'peripherals',
    image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=800&h=800&fit=crop',
    ],
    tags: ['ps4', 'mando'],
    stock: 12,
    rating: 4.6,
    seminuevo: true,
    platform: 'PS4',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '23',
    name: 'Auriculares Gaming RGB 7.1',
    description:
      'Auriculares con sonido surround virtual 7.1, micrófono y luces RGB. Multiplataforma.',
    price: 79,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=800&fit=crop',
    ],
    tags: ['audio', 'rgb', 'headset'],
    stock: 15,
    rating: 4.3,
    platform: 'Multi',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '24',
    name: 'Teclado Mecánico RGB',
    description:
      'Teclado mecánico con switches lineales e iluminación RGB personalizable.',
    price: 149,
    category: 'peripherals',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=800&h=800&fit=crop',
    ],
    tags: ['teclado', 'rgb', 'mecánico'],
    stock: 8,
    rating: 4.5,
    platform: 'PC',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '25',
    name: 'Horizon Forbidden West Complete Edition',
    description:
      'Horizon Forbidden West Complete Edition con Burning Shores. Mundo abierto épico.',
    price: 120,
    category: 'games',
    ...steam('2420110'),
    tags: ['ps5', 'acción', 'horizon'],
    stock: 4,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '26',
    name: 'Death Stranding Director\'s Cut',
    description:
      "Death Stranding Director's Cut. Obra de Hideo Kojima en perfecto estado.",
    price: 55,
    category: 'games',
    ...steam('1850570'),
    tags: ['ps5', 'aventura', 'kojima'],
    stock: 5,
    rating: 4.6,
    seminuevo: true,
    platform: 'PS5 / PC',
    genre: 'Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '27',
    name: 'Sekiro: Shadows Die Twice',
    description:
      'Sekiro: Shadows Die Twice GOTY. Combate samurái exigente de FromSoftware.',
    price: 50,
    category: 'games',
    ...steam('814380'),
    tags: ['ps4', 'acción', 'souls'],
    stock: 6,
    rating: 4.9,
    featured: true,
    platform: 'PS4 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '28',
    name: 'Dark Souls III',
    description:
      'Dark Souls III. El clásico souls-like. Disco seminuevo sin rayones.',
    price: 35,
    category: 'games',
    ...steam('374320'),
    tags: ['ps4', 'rpg', 'souls'],
    stock: 7,
    rating: 4.8,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'RPG / Acción',
    ageRating: 'Adultos',
  },
  {
    id: '29',
    name: 'Detroit: Become Human',
    description:
      'Detroit: Become Human. Historia interactiva de androides. Como nuevo.',
    price: 40,
    category: 'games',
    ...steam('1222140'),
    tags: ['ps4', 'aventura', 'narrativo'],
    stock: 5,
    rating: 4.7,
    featured: true,
    platform: 'PS4 / PC',
    genre: 'Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '30',
    name: 'It Takes Two',
    description:
      'It Takes Two. Aventura cooperativa ganadora del GOTY. Ideal para jugar en pareja.',
    price: 60,
    category: 'games',
    ...steam('1426210'),
    tags: ['ps5', 'cooperativo', 'aventura'],
    stock: 4,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Aventura / Cooperativo',
    ageRating: 'Adolescentes',
  },
  {
    id: '31',
    name: 'Baldur\'s Gate 3',
    description:
      "Baldur's Gate 3. RPG del año con combate táctico y libertad total.",
    price: 140,
    category: 'games',
    ...steam('1086940'),
    tags: ['ps5', 'rpg', 'd&d'],
    stock: 3,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '32',
    name: 'The Witcher 3: Wild Hunt',
    description:
      'The Witcher 3 Complete Edition. Incluye expansiones Hearts of Stone y Blood and Wine.',
    price: 45,
    category: 'games',
    ...steam('292030'),
    tags: ['ps4', 'rpg', 'witcher'],
    stock: 8,
    rating: 4.9,
    seminuevo: true,
    featured: true,
    platform: 'PS4 / PS5',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '33',
    name: 'Black Myth: Wukong',
    description:
      'Black Myth: Wukong. Acción souls-like inspirada en Journey to the West.',
    price: 160,
    category: 'games',
    ...steam('2358720'),
    tags: ['ps5', 'acción', 'wukong'],
    stock: 4,
    rating: 4.8,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '34',
    name: 'Lies of P',
    description:
      'Lies of P. Souls-like inspirado en Pinocho. Combate preciso y atmósfera gótica.',
    price: 85,
    category: 'games',
    ...steam('1627720'),
    tags: ['ps5', 'souls', 'acción'],
    stock: 5,
    rating: 4.7,
    platform: 'PS5 / PC',
    genre: 'Acción / RPG',
    ageRating: 'Adultos',
  },
  {
    id: '35',
    name: 'Alan Wake 2',
    description:
      'Alan Wake 2. Terror psicológico de Remedy. Disco en excelente estado.',
    price: 130,
    category: 'games',
    ...steam('1902960'),
    tags: ['ps5', 'terror', 'aventura'],
    stock: 3,
    rating: 4.8,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Terror / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '36',
    name: 'Resident Evil Village',
    description:
      'Resident Evil Village. Terror en la aldea. Incluye modo Mercenarios.',
    price: 55,
    category: 'games',
    ...steam('1196590'),
    tags: ['ps5', 'terror', 're'],
    stock: 6,
    rating: 4.7,
    seminuevo: true,
    platform: 'PS5 / PC',
    genre: 'Terror / Acción',
    ageRating: 'Adultos',
  },
  {
    id: '37',
    name: 'Resident Evil 2 Remake',
    description:
      'Resident Evil 2 Remake. Clásico reinventado. Leon y Claire en Raccoon City.',
    price: 40,
    category: 'games',
    ...steam('883710'),
    tags: ['ps4', 'terror', 're'],
    stock: 7,
    rating: 4.9,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Terror',
    ageRating: 'Adultos',
  },
  {
    id: '38',
    name: 'Dead Space Remake',
    description:
      'Dead Space Remake. Terror espacial reconstruido desde cero.',
    price: 90,
    category: 'games',
    ...steam('1693980'),
    tags: ['ps5', 'terror', 'sci-fi'],
    stock: 4,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'Terror / Acción',
    ageRating: 'Adultos',
  },
  {
    id: '39',
    name: 'Street Fighter 6',
    description:
      'Street Fighter 6. El mejor fighting de Capcom con World Tour y ranked.',
    price: 100,
    category: 'games',
    ...steam('1364780'),
    tags: ['ps5', 'lucha', 'sf6'],
    stock: 5,
    rating: 4.8,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Lucha',
    ageRating: 'Adolescentes',
  },
  {
    id: '40',
    name: 'Tekken 8',
    description:
      'Tekken 8. Combate 3D brutal con gráficos de nueva generación.',
    price: 125,
    category: 'games',
    ...steam('1778820'),
    tags: ['ps5', 'lucha', 'tekken'],
    stock: 4,
    rating: 4.7,
    platform: 'PS5 / PC',
    genre: 'Lucha',
    ageRating: 'Adolescentes',
  },
  {
    id: '41',
    name: 'Persona 5 Royal',
    description:
      'Persona 5 Royal. JRPG definitivo de Atlus. Historia, estilo y turnos.',
    price: 70,
    category: 'games',
    ...steam('1687950'),
    tags: ['ps5', 'rpg', 'persona'],
    stock: 5,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '42',
    name: 'Persona 3 Reload',
    description:
      'Persona 3 Reload. Remake moderno del clásico de Atlus.',
    price: 110,
    category: 'games',
    ...steam('2161700'),
    tags: ['ps5', 'rpg', 'persona'],
    stock: 4,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '43',
    name: 'NieR: Automata',
    description:
      'NieR: Automata Game of the Yorha Edition. Acción y narrativa única de Yoko Taro.',
    price: 45,
    category: 'games',
    ...steam('524220'),
    tags: ['ps4', 'acción', 'rpg'],
    stock: 6,
    rating: 4.9,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Acción / RPG',
    ageRating: 'Adultos',
  },
  {
    id: '44',
    name: 'Final Fantasy VII Remake',
    description:
      'Final Fantasy VII Remake Intergrade. Cloud y Sephiroth en Midgar.',
    price: 80,
    category: 'games',
    ...steam('1462040'),
    tags: ['ps5', 'rpg', 'ff7'],
    stock: 4,
    rating: 4.8,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adolescentes',
  },
  {
    id: '45',
    name: 'Monster Hunter: World',
    description:
      'Monster Hunter: World. Caza cooperativa en un ecosistema vivo.',
    price: 35,
    category: 'games',
    ...steam('582010'),
    tags: ['ps4', 'acción', 'cooperativo'],
    stock: 8,
    rating: 4.7,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Acción',
    ageRating: 'Adolescentes',
  },
  {
    id: '46',
    name: 'Helldivers 2',
    description:
      'Helldivers 2. Shooter cooperativo caótico por la Super Tierra.',
    price: 95,
    category: 'games',
    ...steam('553850'),
    tags: ['ps5', 'shooter', 'cooperativo'],
    stock: 5,
    rating: 4.6,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Shooter / Cooperativo',
    ageRating: 'Adultos',
  },
  {
    id: '47',
    name: 'DOOM Eternal',
    description:
      'DOOM Eternal. Acción frenética al máximo. Disco en perfecto estado.',
    price: 40,
    category: 'games',
    ...steam('782330'),
    tags: ['ps4', 'shooter', 'doom'],
    stock: 7,
    rating: 4.8,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Shooter',
    ageRating: 'Adultos',
  },
  {
    id: '48',
    name: 'Stray',
    description:
      'Stray. Aventura como gato en una ciudad cyberpunk. Ideal para todos.',
    price: 55,
    category: 'games',
    ...steam('1332010'),
    tags: ['ps5', 'aventura', 'indie'],
    stock: 6,
    rating: 4.7,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Aventura',
    ageRating: 'Todos',
  },
  {
    id: '49',
    name: 'Hades',
    description:
      'Hades. Roguelike de Supergiant con combate adictivo y narrativa brillante.',
    price: 45,
    category: 'games',
    ...steam('1145360'),
    tags: ['ps5', 'roguelike', 'indie'],
    stock: 8,
    rating: 4.9,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Roguelike / Acción',
    ageRating: 'Adolescentes',
  },
  {
    id: '50',
    name: 'Hollow Knight',
    description:
      'Hollow Knight. Metroidvania de culto en Hallownest. Seminuevo.',
    price: 30,
    category: 'games',
    ...steam('367520'),
    tags: ['ps4', 'metroidvania', 'indie'],
    stock: 10,
    rating: 4.9,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Metroidvania',
    ageRating: 'Todos',
  },
  {
    id: '51',
    name: 'Stardew Valley',
    description:
      'Stardew Valley. Simulador de granja relajante y adictivo.',
    price: 35,
    category: 'games',
    ...steam('413150'),
    tags: ['ps4', 'simulación', 'indie'],
    stock: 9,
    rating: 4.9,
    platform: 'PS4 / PC',
    genre: 'Simulación',
    ageRating: 'Todos',
  },
  {
    id: '52',
    name: 'Palworld',
    description:
      'Palworld. Captura Pals, construye bases y sobrevive. Éxito viral.',
    price: 75,
    category: 'games',
    ...steam('1623730'),
    tags: ['ps5', 'supervivencia', 'multijugador'],
    stock: 5,
    rating: 4.4,
    featured: true,
    platform: 'PS5 / PC',
    genre: 'Supervivencia / Aventura',
    ageRating: 'Adolescentes',
  },
  {
    id: '53',
    name: 'Balatro',
    description:
      'Balatro. Roguelike de póker adictivo. Ideal para partidas cortas.',
    price: 40,
    category: 'games',
    ...steam('2379780'),
    tags: ['ps5', 'indie', 'roguelike'],
    stock: 8,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'Cartas / Roguelike',
    ageRating: 'Adolescentes',
  },
  {
    id: '54',
    name: 'Dave the Diver',
    description:
      'Dave the Diver. Buceo de día, restaurante de noche. Joya indie.',
    price: 50,
    category: 'games',
    ...steam('1868140'),
    tags: ['ps5', 'indie', 'aventura'],
    stock: 6,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'Aventura / Simulación',
    ageRating: 'Todos',
  },
  {
    id: '55',
    name: 'Like a Dragon: Infinite Wealth',
    description:
      'Like a Dragon: Infinite Wealth. JRPG de Yakuza en Hawái y Japón.',
    price: 135,
    category: 'games',
    ...steam('2072450'),
    tags: ['ps5', 'rpg', 'yakuza'],
    stock: 3,
    rating: 4.8,
    platform: 'PS5 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '56',
    name: 'Starfield',
    description:
      'Starfield. RPG espacial de Bethesda. Explora más de 1000 planetas.',
    price: 100,
    category: 'games',
    ...steam('1716740'),
    tags: ['xbox', 'rpg', 'espacio'],
    stock: 4,
    rating: 4.2,
    platform: 'Xbox / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '57',
    name: 'Skyrim Special Edition',
    description:
      'The Elder Scrolls V: Skyrim Special Edition. El RPG de mundo abierto definitivo.',
    price: 40,
    category: 'games',
    ...steam('489830'),
    tags: ['ps4', 'rpg', 'skyrim'],
    stock: 7,
    rating: 4.8,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '58',
    name: 'Fallout 4',
    description:
      'Fallout 4 Game of the Year Edition. Supervivencia post-apocalíptica.',
    price: 35,
    category: 'games',
    ...steam('377160'),
    tags: ['ps4', 'rpg', 'fallout'],
    stock: 6,
    rating: 4.5,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'RPG',
    ageRating: 'Adultos',
  },
  {
    id: '59',
    name: 'Control Ultimate Edition',
    description:
      'Control Ultimate Edition. Acción sobrenatural de Remedy con DLCs incluidos.',
    price: 45,
    category: 'games',
    ...steam('870780'),
    tags: ['ps5', 'acción', 'aventura'],
    stock: 5,
    rating: 4.7,
    platform: 'PS5 / PC',
    genre: 'Acción / Aventura',
    ageRating: 'Adultos',
  },
  {
    id: '60',
    name: 'Little Nightmares II',
    description:
      'Little Nightmares II. Terror y puzzles en un mundo inquietante.',
    price: 40,
    category: 'games',
    ...steam('860510'),
    tags: ['ps4', 'terror', 'puzzle'],
    stock: 6,
    rating: 4.6,
    seminuevo: true,
    platform: 'PS4 / PC',
    genre: 'Terror / Puzzle',
    ageRating: 'Adolescentes',
  },
  {
    id: '61',
    name: 'Xbox Series S',
    description:
      'Consola Xbox Series S 512GB. Compacta, rápida y lista para Game Pass.',
    price: 1400,
    category: 'consoles',
    image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1605901309584-818e25960a8f?w=800&h=800&fit=crop',
    ],
    tags: ['xbox', 'consola'],
    stock: 2,
    rating: 4.6,
    seminuevo: true,
    featured: true,
    platform: 'Xbox',
    genre: 'Consolas',
    ageRating: 'Todos',
  },
  {
    id: '62',
    name: 'Nintendo Switch OLED',
    description:
      'Nintendo Switch OLED 64GB. Pantalla vibrante, dock y Joy-Cons incluidos.',
    price: 1600,
    category: 'consoles',
    image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=800&h=800&fit=crop',
    ],
    tags: ['nintendo', 'switch', 'consola'],
    stock: 3,
    rating: 4.8,
    featured: true,
    platform: 'Nintendo Switch',
    genre: 'Consolas',
    ageRating: 'Todos',
  },
  {
    id: '63',
    name: 'Ratón Gaming RGB 16K DPI',
    description:
      'Ratón ultraligero con sensor de 16K DPI, 6 botones programables y RGB.',
    price: 89,
    category: 'peripherals',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=800&fit=crop',
    ],
    tags: ['ratón', 'rgb', 'pc'],
    stock: 14,
    rating: 4.5,
    platform: 'PC',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '64',
    name: 'Silla Gamer Ergonómica',
    description:
      'Silla gamer con soporte lumbar, reclinable 180° y cojines ajustables.',
    price: 450,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&h=800&fit=crop',
    ],
    tags: ['silla', 'ergonomía', 'setup'],
    stock: 4,
    rating: 4.4,
    platform: 'Multi',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '65',
    name: 'Monitor Gaming 27" 165Hz',
    description:
      'Monitor 27" IPS 165Hz 1ms. Ideal para competitive y single player.',
    price: 780,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=800&fit=crop',
    ],
    tags: ['monitor', '165hz', 'pc'],
    stock: 3,
    rating: 4.6,
    featured: true,
    platform: 'PC',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '66',
    name: 'Base de Carga DualSense',
    description:
      'Estación de carga oficial para dos mandos DualSense. LED de estado.',
    price: 95,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=800&h=800&fit=crop',
    ],
    tags: ['ps5', 'carga', 'accesorio'],
    stock: 10,
    rating: 4.5,
    platform: 'PS5',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '67',
    name: 'Memoria SSD NVMe 1TB',
    description:
      'SSD NVMe Gen4 1TB. Ideal para ampliar PS5 o PC gaming.',
    price: 320,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=800&fit=crop',
    ],
    tags: ['ssd', 'almacenamiento', 'ps5'],
    stock: 8,
    rating: 4.7,
    platform: 'PS5 / PC',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
  {
    id: '68',
    name: 'Webcam Full HD Streaming',
    description:
      'Webcam 1080p 60fps con micrófono dual. Perfecta para streams y Discord.',
    price: 130,
    category: 'accessories',
    image: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&h=800&fit=crop',
    ],
    tags: ['webcam', 'streaming', 'pc'],
    stock: 7,
    rating: 4.3,
    platform: 'PC',
    genre: 'Accesorios',
    ageRating: 'Todos',
  },
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  getAll(): Product[] {
    return PRODUCTS;
  }

  getFeatured(): Product[] {
    return PRODUCTS.filter((product) => product.featured).slice(0, 18);
  }

  getById(id: string): Product | undefined {
    return PRODUCTS.find((product) => product.id === id);
  }

  getByCategory(category: ProductCategory | 'all'): Product[] {
    if (category === 'all') {
      return PRODUCTS;
    }
    return PRODUCTS.filter((product) => product.category === category);
  }

  getRelated(product: Product, limit = 4): Product[] {
    return PRODUCTS.filter(
      (item) => item.category === product.category && item.id !== product.id
    ).slice(0, limit);
  }

  search(term: string): Product[] {
    const query = term.trim().toLowerCase();
    if (!query) {
      return PRODUCTS;
    }
    return PRODUCTS.filter(
      (product) =>
        product.name.toLowerCase().includes(query) ||
        product.tags.some((tag) => tag.includes(query)) ||
        (product.genre?.toLowerCase().includes(query) ?? false)
    );
  }
}
